# Generated by Django 4.1.7 on 2023-07-22 02:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата удаления')),
                ('name_counterparty', models.CharField(max_length=50, verbose_name='Имя (Название):')),
                ('inn_individuals', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='ИНН')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона: ')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'db_table': 'socks_factory_counterparty',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата удаления')),
                ('name_department', models.CharField(max_length=50, verbose_name='Подразделение:')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'db_table': 'socks_factory_department',
            },
        ),
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата удаления')),
                ('birthday', models.DateField(verbose_name='Дата рождения: ')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина'), ('O', 'Неизвестно')], max_length=50, verbose_name='Пол: ')),
                ('second_name_individuals', models.CharField(max_length=50, verbose_name='Фамилия:')),
                ('first_name_individuals', models.CharField(max_length=50, verbose_name='Имя:')),
                ('surname_individuals', models.CharField(max_length=50, verbose_name='Отчество:')),
                ('full_name_individuals', models.CharField(max_length=100, null=True, verbose_name='Полное имя:')),
                ('inn_individuals', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='ИНН')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона: ')),
                ('biography', models.TextField(null=True, verbose_name='Биография: ')),
            ],
            options={
                'verbose_name': 'Физ.лицо',
                'verbose_name_plural': 'Физ.лица',
                'db_table': 'socks_factory_individuals',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата удаления')),
                ('name_jobTitle', models.CharField(max_length=50, verbose_name='Должность:')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'socks_factory_jobTitle',
            },
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата удаления')),
                ('date_of_employment', models.DateField(verbose_name='Дата приянятия на работу: ')),
                ('salary', models.IntegerField(verbose_name='Оклад (Зарплата): ')),
                ('department_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soksfactory.department', verbose_name='Подразделение:')),
                ('individuals_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soksfactory.individuals', verbose_name='Физ.Лицо:')),
                ('job_title_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soksfactory.jobtitle', verbose_name='Должность:')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'socks_factory_employes',
            },
        ),
    ]
