# Generated by Django 4.1.7 on 2023-07-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soksfactory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterparty",
            name="deleted_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="deleted_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
        migrations.AlterField(
            model_name="employes",
            name="deleted_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
        migrations.AlterField(
            model_name="individuals",
            name="biography",
            field=models.TextField(blank=True, null=True, verbose_name="Биография: "),
        ),
        migrations.AlterField(
            model_name="individuals",
            name="deleted_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
        migrations.AlterField(
            model_name="jobtitle",
            name="deleted_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
    ]
