# Generated by Django 4.1.7 on 2023-07-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("soksfactory", "0002_alter_counterparty_deleted_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeSpecialKeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "name_type_special_keys",
                    models.CharField(max_length=50, verbose_name="Вид Ключа :"),
                ),
            ],
            options={
                "verbose_name": "Вид Ключа",
                "verbose_name_plural": "Вид Ключа",
                "db_table": "socks_factory_type_special_keys",
            },
        ),
        migrations.CreateModel(
            name="SpecialKeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "name_special_keys",
                    models.CharField(max_length=50, verbose_name="Ключь :"),
                ),
                (
                    "type_special_keys_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soksfactory.typespecialkeys",
                        verbose_name="Вид Ключа :",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ключь",
                "verbose_name_plural": "Ключь",
                "db_table": "socks_factory_special_keys",
            },
        ),
    ]
