# Generated by Django 4.1.7 on 2023-07-26 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soksfactory", "0003_typespecialkeys_specialkeys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individuals",
            name="full_name_individuals",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Полное имя:"
            ),
        ),
        migrations.AlterField(
            model_name="individuals",
            name="inn_individuals",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(14)],
                verbose_name="ИНН",
            ),
        ),
    ]
