# Generated by Django 4.1.7 on 2023-07-29 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("soksfactory", "0004_alter_individuals_full_name_individuals_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryNomenclature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "name_category_nomenclature",
                    models.CharField(
                        max_length=50, verbose_name="Категория номенклатуры :"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория номенклатуры",
                "verbose_name_plural": "Категория номенклатуры",
                "db_table": "socks_factory_category_nomenclature",
            },
        ),
        migrations.CreateModel(
            name="CharacteristicDOC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "name_сharacteristic",
                    models.CharField(max_length=50, verbose_name="Характеристика : "),
                ),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристика",
                "db_table": "socks_factory_characteristic_DOC",
            },
        ),
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "name_nomenclature",
                    models.CharField(max_length=50, verbose_name="Номенклатура"),
                ),
                (
                    "category_nomenclature_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soksfactory.categorynomenclature",
                        verbose_name="Категория номенклатуры :",
                    ),
                ),
            ],
            options={
                "verbose_name": "Номенклатура",
                "verbose_name_plural": "Номенклатура",
                "db_table": "socks_factory_nomenclature",
            },
        ),
        migrations.CreateModel(
            name="Panton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "color_name",
                    models.CharField(max_length=100, verbose_name="Пантон : "),
                ),
            ],
            options={
                "verbose_name": "Пантон",
                "verbose_name_plural": "Пантон",
                "db_table": "socks_factory_pantone",
            },
        ),
        migrations.CreateModel(
            name="PropertyChar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "property_char_name",
                    models.CharField(max_length=50, verbose_name="Свойство :"),
                ),
            ],
            options={
                "verbose_name": "Свойство",
                "verbose_name_plural": "Свойство",
                "db_table": "socks_factory_property_char",
            },
        ),
        migrations.CreateModel(
            name="SpecificationDOC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "name_specification",
                    models.CharField(
                        max_length=50, verbose_name="Название спецификации : "
                    ),
                ),
                (
                    "characteristic_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soksfactory.characteristicdoc",
                        verbose_name="Характеристика :",
                    ),
                ),
                (
                    "special_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soksfactory.specialkeys",
                        verbose_name="Ключ :",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение",
                "verbose_name_plural": "Значение",
                "db_table": "socks_factory_specificationDOC",
            },
        ),
        migrations.CreateModel(
            name="TypeNomenclature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "name_type_nomenclature",
                    models.CharField(
                        max_length=50, verbose_name="Группа номенклатуры :"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид номенклатуры",
                "verbose_name_plural": "Вид номенклатуры",
                "db_table": "socks_factory_type_nomenclature",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "unit_name",
                    models.CharField(
                        max_length=100, verbose_name="Единица измерения : "
                    ),
                ),
            ],
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единица измерения",
                "db_table": "socks_factory_unit",
            },
        ),
        migrations.CreateModel(
            name="ValueChar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "value_char",
                    models.CharField(max_length=50, verbose_name="Значение : "),
                ),
                (
                    "property_char_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soksfactory.propertychar",
                        verbose_name="Свойство :",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение",
                "verbose_name_plural": "Значение",
                "db_table": "socks_factory_value_char",
            },
        ),
        migrations.CreateModel(
            name="SpecificationITEM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="Значение : "
                    ),
                ),
                ("unit", models.CharField(max_length=50, verbose_name="")),
                (
                    "material_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soksfactory.nomenclature",
                        verbose_name="Материал :",
                    ),
                ),
                (
                    "specificationDOC_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soksfactory.specificationdoc",
                        verbose_name="Документ :",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение",
                "verbose_name_plural": "Значение",
                "db_table": "socks_factory_specificationITEM",
            },
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="type_nomenclature_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soksfactory.typenomenclature",
                verbose_name="Вид номенклатуры:",
            ),
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "color_note",
                    models.CharField(
                        max_length=100, verbose_name="Примечание к цвету :"
                    ),
                ),
                (
                    "color_name",
                    models.CharField(max_length=200, verbose_name="Цвет : "),
                ),
                (
                    "pantone_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soksfactory.panton",
                        verbose_name="Пантон :",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет",
                "verbose_name_plural": "Цвет",
                "db_table": "socks_factory_color",
            },
        ),
        migrations.CreateModel(
            name="CharacteristicITEM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                ("text_name", models.CharField(max_length=50, verbose_name="Текст : ")),
                (
                    "characteristic_doc_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soksfactory.characteristicdoc",
                        verbose_name="Номенклатура :",
                    ),
                ),
                (
                    "property_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soksfactory.propertychar",
                        verbose_name="Свойство :",
                    ),
                ),
                (
                    "value_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soksfactory.valuechar",
                        verbose_name="Значение :",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика элемент",
                "verbose_name_plural": "Характеристика элемент",
                "db_table": "socks_factory_characteristic_ITEM",
            },
        ),
        migrations.AddField(
            model_name="characteristicdoc",
            name="nomenclature_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soksfactory.nomenclature",
                verbose_name="Номенклатура :",
            ),
        ),
    ]
