# Generated by Django 4.1.7 on 2023-08-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soksfactory", "0006_alter_specificationdoc_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specificationdoc",
            options={
                "verbose_name": "Спецификация (Калькуляция)",
                "verbose_name_plural": "Спецификация (Калькуляция)",
            },
        ),
        migrations.AddField(
            model_name="characteristicdoc",
            name="characteristic_note",
            field=models.CharField(
                default=123, max_length=50, verbose_name="Примечание к характеристике"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="characteristicdoc",
            name="name_сharacteristic",
            field=models.CharField(
                blank=True,
                max_length=100,
                unique=True,
                verbose_name="Характеристика : ",
            ),
        ),
        migrations.AlterField(
            model_name="specificationitem",
            name="unit",
            field=models.CharField(max_length=50, verbose_name="Единица измерения"),
        ),
    ]
