# Generated by Django 4.1.7 on 2023-08-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soksfactory", "0007_alter_specificationdoc_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteristicdoc",
            name="name_сharacteristic",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Характеристика : "
            ),
        ),
    ]
