# Generated by Django 4.1.7 on 2023-08-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("soksfactory", "0008_alter_characteristicdoc_name_сharacteristic"),
    ]

    operations = [
        migrations.AddField(
            model_name="specificationitem",
            name="type_nomenclature_sp_fk",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="soksfactory.typenomenclature",
                verbose_name="Вид номенклатуры:",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="characteristicdoc",
            name="name_сharacteristic",
            field=models.CharField(
                blank=True,
                max_length=100,
                unique=True,
                verbose_name="Характеристика : ",
            ),
        ),
        migrations.AlterField(
            model_name="characteristicitem",
            name="characteristic_doc_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soksfactory.characteristicdoc",
                verbose_name="Характеристика :",
            ),
        ),
        migrations.AlterField(
            model_name="characteristicitem",
            name="text_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Текст : "),
        ),
    ]
